### ISSUE TITLE
Malformed MARC file causes infinite loop

### ISSUE THREAD

**Issue by demiankatz** [solrmarc/solrmarc#101]
When I try to index this apparently-corrupted MARC file ([bad-marc-file.zip](https://github.com/solrmarc/solrmarc/files/11599483/bad-marc-file.zip)), SolrMarc (v3.4, the latest release as of this writing) displays this error message:

```
Exception in thread "MarcReader-Thread" java.lang.StringIndexOutOfBoundsException: offset 0, count 14, length 2
	at java.base/java.lang.String.checkBoundsOffCount(String.java:3304)
	at java.base/java.lang.String.<init>(String.java:591)
	at org.marc4j.MarcPermissiveStreamReader.parseRecord(MarcPermissiveStreamReader.java:727)
	at org.marc4j.MarcPermissiveStreamReader.next(MarcPermissiveStreamReader.java:365)
	at org.solrmarc.driver.Indexer.getRecord(Indexer.java:208)
	at org.solrmarc.driver.MarcReaderThread.run(MarcReaderThread.java:33)
```

It then hangs seemingly forever.

If I hit ^C to break out, the screen begins flooding with an infinite loop of these messages:

```
WARN [main] (ThreadedIndexer.java:164) - ThreadedIndexer at top of loop, shutting down
WARN [main] (ThreadedIndexer.java:179) - ThreadedIndexer flushing 0 docs from docQ, which contains 0 documents
```

At this point, nothing will stop the process except for a `kill -9` command.

I feel like I have encountered variations of this problem in the past where the exception handling seemed a little bit off, but I couldn't find an existing issue tracking it.

@haschart, any idea what is happening here? Seems like a bug we ought to try to squash.... Let me know if I can do anything to help!

**Comment by haschart** [comment]
I think the error it is encountering causes the bytes for the record to remain marked as unread.  so the next time it tries, it encounters the same error, and continues.

That is a really messed up record, but it shouldn't cause an infinite loop.

-Bob

________________________________
From: Demian Katz ***@***.***>
Sent: Tuesday, May 30, 2023 7:40 AM
To: solrmarc/solrmarc ***@***.***>
Cc: Haschart, Robert J (rh9ec) ***@***.***>; Mention ***@***.***>
Subject: [solrmarc/solrmarc] Malformed MARC file causes infinite loop (Issue #101)


When I try to index this apparently-corrupted MARC file (bad-marc-file.zip<https://github.com/solrmarc/solrmarc/files/11599483/bad-marc-file.zip>), SolrMarc (v3.4, the latest release as of this writing) displays this error message:

Exception in thread "MarcReader-Thread" java.lang.StringIndexOutOfBoundsException: offset 0, count 14, length 2
        at java.base/java.lang.String.checkBoundsOffCount(String.java:3304)
        at java.base/java.lang.String.<init>(String.java:591)
        at org.marc4j.MarcPermissiveStreamReader.parseRecord(MarcPermissiveStreamReader.java:727)
        at org.marc4j.MarcPermissiveStreamReader.next(MarcPermissiveStreamReader.java:365)
        at org.solrmarc.driver.Indexer.getRecord(Indexer.java:208)
        at org.solrmarc.driver.MarcReaderThread.run(MarcReaderThread.java:33)


It then hangs seemingly forever.

If I hit ^C to break out, the screen begins flooding with an infinite loop of these messages:

WARN [main] (ThreadedIndexer.java:164) - ThreadedIndexer at top of loop, shutting down
WARN [main] (ThreadedIndexer.java:179) - ThreadedIndexer flushing 0 docs from docQ, which contains 0 documents


At this point, nothing will stop the process except for a kill -9 command.

I feel like I have encountered variations of this problem in the past where the exception handling seemed a little bit off, but I couldn't find an existing issue tracking it.

@haschart<https://github.com/haschart>, any idea what is happening here? Seems like a bug we ought to try to squash.... Let me know if I can do anything to help!

**Comment by haschart** [comment]
What version of solrmarc are you using   (ie the version of the solrmarc_core file)

I've generated a new marc4j jar, and a new release of solrmarc, but even with the older solrmarc_core jar I did not see that infinite loop error when operating on that bad marc file.

It may be that code has been checked into the git repo for solrmarc without a new release being generated.

In any case I should be able to push a new release in the next day or so.

-Bob Haschart

________________________________

**Comment by demiankatz** [comment]
@haschart, I'm using the v3.4 bundled with VuFind -- you can find the exact .jar here:

https://github.com/vufind-org/vufind/blob/dev/import/solrmarc_core_3.4.jar

I'll be happy to test this again with the new release when it's ready. Thanks!

**Comment by demiankatz** [comment]
Thanks, @haschart -- I think we're half-way there, at least. When I build the code from the 3.5 branch, it still hangs at the exception message:

```
Exception in thread "MarcReader-Thread" java.lang.StringIndexOutOfBoundsException: offset 0, count 14, length 2
	at java.base/java.lang.String.checkBoundsOffCount(String.java:3304)
	at java.base/java.lang.String.<init>(String.java:591)
	at org.marc4j.MarcPermissiveStreamReader.parseRecord(MarcPermissiveStreamReader.java:727)
	at org.marc4j.MarcPermissiveStreamReader.next(MarcPermissiveStreamReader.java:365)
	at org.solrmarc.driver.Indexer.getRecord(Indexer.java:208)
	at org.solrmarc.driver.MarcReaderThread.run(MarcReaderThread.java:33)
```

...but then when I hit ^C, it actually stops instead of going into the infinite loop like before.

But ideally, it would be nice if the exception caused SolrMarc to stop running, instead of to hang until ^C is hit. Otherwise, a record like this can cause an automated process to hang forever.

**Comment by haschart** [comment]
Your post helped me track down a specific path where the freeze-up occurs as you describe.  However it seems that in your test it is using the previous version of marc4j,  not the newly released version 2.9.5 which should prevent that String Out Of Bounds error from even happening.

If you find the log4j.properties that is being used and change the line :
log4j.logger.org.solrmarc.driver.Boot=INFO
to
log4j.logger.org.solrmarc.driver.Boot=DEBUG
it should show you the libraries it is loading and using as the program starts.

-Bob


________________________________

**Comment by demiankatz** [comment]
Thanks, @haschart, you're right -- I built a new copy of the solrmarc jar and copied it into my VuFind instance, but I neglected to update the other dependencies when I was testing. In any case, I'm glad it helped reveal a problem! Happy to test again if you need me to, with or without outdated marc4j jars. ;-)

**Comment by haschart** [comment]
I did find where the freeze-up was occurring and made another draft release containing the change.

-Bob

________________________________

**Comment by demiankatz** [comment]
Thanks, @haschart -- I did some more testing and concur that the problem is now fully solved. We can close this issue once 3.5 is officially released!

**Comment by haschart** [comment]
3.5 is now full released.

Yay.

-Bob Haschart
________________________________

**Comment by demiankatz** [comment]
Thanks, @haschart! One small note: I noticed that the required_jars_3.5.zip file currently attached to the release contains both the old and the new version of marc4j -- probably worth deleting the old one and re-uploading it. In any case, that's a separate matter, so I'm going to close this issue now. :-)
