### ISSUE TITLE
refactor:  split SolrIndexer and tools.Utils into smaller classes

### ISSUE THREAD

**Issue by GoogleCodeExporter** [solrmarc/solrmarc#20]
```
Suggestion:

Split tools.Utils  into
DateUtils
MarcUtils
PropertiesUtils

SolrIndexer:   push more functionality into utils classes (as static methods)
```

Original issue reported on code.google.com by `naomi.du...@gmail.com` on 9 Jan 2010 at 11:45

**Comment by haschart** [comment]
The new version splits the classes and completely re-organizes what used to be in the SolrIndexer class.
