### ISSUE TITLE
Reconstitute Wiki pages from Google Code

### ISSUE THREAD

**Issue by adjam** [solrmarc/solrmarc#33]
Google Code exported wiki pages in the `wiki` branch. 

I followed this process in my fork: https://github.com/adjam/solrmarc/wiki 

1. create an initial wiki page for this repository (repository admin uses the 'wiki' link at the top of the github page for the repo and creates a simple splash page via the UI)
2. Clone  the '.wiki' repository for this one, viz. `git clone https;//github.com/solrmarc/solrmarc.wiki.git solrmarc-wiki` 
3. In your local `solrmarc` repository, checkout the `wiki` branch; your directory will now be full of the `.md` files.
4. `cp *.md ../solrmarc-wiki` (or wherever)
5. In the "solrmarc-wiki" repository, add all the `.md` files, commit, and push

HTH and thanks

**Comment by haschart** [comment]
Pages added.  Thanks
