### ISSUE TITLE
fieldSpec with brackets:  for control field, it should mean byte sequence; for non-control field, it should mean regex pattern

### ISSUE THREAD

**Issue by GoogleCodeExporter** [solrmarc/solrmarc#7]
```
Code currently treats numeric chars in brackets as a byte sequence:

008[7-12]

but treats non-numeric as a regex pattern:

650[a-dg-p]

Since subfields can be numeric, a better solution is to assume it's a byte
sequence for control fields (leader, 0 < tag <= 9), and a regex pattern for
other fields.



```

Original issue reported on code.google.com by `naomi.du...@gmail.com` on 21 Aug 2009 at 6:10

**Comment by haschart** [comment]
This behavior is now supported by the latest changes to the JFlex scanner and Java Cup parser in the commit https://github.com/solrmarc/solrmarc/commit/60c6333566cec4fa4a32fdd8bcabf893c6b3d5d7 in the "next" branch
